### ISSUE TITLE
would you be able to post the dockerfile for your image?

### ISSUE THREAD

**Issue by jdonnelly-apixio** [mykidong/hive-on-spark-in-kubernetes#1]
hey, this looks great. would you be able to add the dockerfile for `mykidong/hivemetastore:v3.0.0` to this repo?

thanks!
Jon

**Comment by mykidong** [comment]
@jdonnelly-apixio    I have added a docker file for hive metastore in `hive-metastore` directory: https://github.com/mykidong/hive-on-spark-in-kubernetes/tree/master/hive-metastore/docker

- Kidong.

**Comment by jdonnelly-apixio** [comment]
Awesome, thank you!
